segler-alex/RadioDroid

- app/src/main/res/values-sk/strings.xml
Translated all the strings as of version 1.14.6. The apps builds fine and shows slovak language strings when the system language is configured to slovak. It is all working as expected.
> Added Slovak language file

- app/build.gradle
- circle.yml
add commands to build on circleCI
> Build with circleCI

- app/src/main/res/values-fr/strings.xml
Improvements and new translations ;)
> Update strings.xml for french translation

- app/src/main/res/values-es/strings.xml
Thanks for releasing a new version of RadioDroid incuding the Spanish translation! Now that I see the strings in my phone, I fixed a typo and did some slight improvements in other strings.
> Update Spanish translation: fix typo and other minor fixes

- app/src/main/res/values-sk/strings.xml
I have made some phrases shorter and less disturbing and translated new ones.
> Updated slovak language file

- app/src/main/res/values-fi/strings.xml
Added finnish translation for audio focus feature.
> request audio focus [finnish translation]

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/RadioAlarmManager.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterRadioAlarm.java
- app/src/main/java/net/programmierecke/radiodroid2/data/DataRadioStationAlarm.java
- app/src/main/res/color/toggle_color.xml
- app/src/main/res/drawable/ic_refresh_black_24dp.xml
- app/src/main/res/layout/day_button.xml
- app/src/main/res/layout/list_item_alarm.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
This PR clones the "repeating" function from the standard android alarm. It enables the user to restrict an alarm to any subset of days of the week.
fixes: https://github.com/segler-alex/RadioDroid/issues/66
> repeating alarms on weekday basis

- README.md
- app/src/main/res/values-fr/strings.xml
Update the french translation with new keys (you can notify me in the future if there is any new key)
This PR also add two buttons with links to fdroid and google play store ;)
Thanks again for this app :)
> Update the french translation + add buttons in README.md

- app/src/main/java/net/programmierecke/radiodroid2/RadioAlarmManager.java
Introducing the weekdays alarm feature broke loading existing alarms. This fixes #121
> fix exception on loading old alarms

- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This greatly reduces the amount of network requests the app makes and enhances privacy.
> Add an option for downloading icons or not

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/ActivityPlayerInfo.java
- app/src/main/java/net/programmierecke/radiodroid2/ActivityRadioStationDetail.java
- app/src/main/java/net/programmierecke/radiodroid2/AlarmReceiver.java
- app/src/main/java/net/programmierecke/radiodroid2/ApplicationSelectorDialog.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentBase.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentCategories.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentRecordings.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java
- app/src/main/java/net/programmierecke/radiodroid2/MPDClient.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerServiceUtil.java
- app/src/main/java/net/programmierecke/radiodroid2/RadioAlarmManager.java
- app/src/main/java/net/programmierecke/radiodroid2/RecordingsManager.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterRadioAlarm.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/data/PlaylistM3UEntry.java
It might not look nice, but the compiler will always optimize the if away since BuildConfig.DEBUG is 'static final'
Edit: Rebased upon e60633ebe3bb2211bccc3d3f17b409087a30c974
> Fix log spam

- app/src/main/AndroidManifest.xml
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
Also fix that media button resume other app after this one and fix media buttons on old APIs.
Fixes #150
> Fix random resume. Fix holding wifi and wake lock while paused. Small refactoring.

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/ApplicationSelectorDialog.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentAlarm.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentBase.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentCategories.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentTabs.java
- app/src/main/java/net/programmierecke/radiodroid2/MPDClient.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/RecordingsManager.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java
- app/src/main/java/net/programmierecke/radiodroid2/TimePickerFragment.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/data/DataRadioStation.java
- app/src/main/java/net/programmierecke/radiodroid2/data/PlaylistM3U.java
- app/src/main/java/net/programmierecke/radiodroid2/data/PlaylistM3UEntry.java
- app/src/main/java/net/programmierecke/radiodroid2/data/ShoutcastInfo.java
IntelliJ suggests a few small fixes that make the code easier to read and remove some unnecessary stuff
> Fix some compilation/IDE warnings

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/HttpClient.java
- app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java
- app/src/main/java/net/programmierecke/radiodroid2/data/ShoutcastInfo.java
I have added okhttp3 library to correctly handle 'ICY 200 OK' responses and tested changes on android 4.1.1, 4.4.4 and 7.1.2.
> fix #165 - Not playing certain radio stations

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
* show all stations (default, as before)
* show favorites (selectable, as in previous version)
* show history (new option)
> fix #159 - add new startup preferences

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
+ added German text strings for #159
+ removed unneeded other language strings
> fix #159 - translation-followup

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
+ make sure to setup the default string
> fix #159 - follow-up: setup default strings

- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
+ improved German preferences texts
+ new order in preferences
> German text improvements

- app/src/main/AndroidManifest.xml
- app/src/main/res/values-de/strings.xml
+ allow i10n of the playerInfo title
+ de: "Wiedergabestatus"
> fix playerInfo title

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/FragmentAbout.java
- app/src/main/res/layout/layout_about.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This pr comprises:
+ apk filename now has buildtype, flavour, version and git hash
+ preference page shows version, git hash and build date
+ text improvements
> Fix apk filename; show version+git+builddate; text improvements

- app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java
+ filename now starts with date YYYYMMDD-HHMMSS_Stationname
+ filename now does not contain spaces
> chg filename recording format: starts with date

- app/src/main/java/net/programmierecke/radiodroid2/ActivityPlayerInfo.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/res/drawable/ic_delete_black_55dp.xml
- app/src/main/res/drawable/ic_fiber_manual_record_black_50dp.xml
- app/src/main/res/drawable/ic_fiber_manual_record_green_50dp.xml
- app/src/main/res/drawable/ic_fiber_manual_record_red_50dp.xml
- app/src/main/res/drawable/ic_stop_black_60dp.xml
- app/src/main/res/layout/layout_about.xml
- app/src/main/res/layout/layout_player_status.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values/strings.xml
+ refactored the play/pause/stop/record function
+ added pause button to playeractivity
+ increased and harmonised the button sizes
+ black pause and stop buttons
+ record button becomes green when storage permission available (green: ready-to-start-recording)
+ record buttons turns red when actively recording
+ "lazy" display of the transferred bytes and, when applicable, the recorded filename
> add pause button to playerinfo; refactored playeraction

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java
- app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java
+ recording filename: append the streamtitle (stream metadata) if available
+ version 0.39
> bump version 0.39; chg recording filename: append the streamtitle if available

- app/build.gradle
@werman problem fixed.
@segler-alex I think this is a big step forward and @werman 's version deserves the next version number ( 0.40 )
> bump version 0.40

- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/layout/list_item_station.xml
> larger icon sizes

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/RadioDroidApp.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/layout/layout_player_status.xml
- app/src/main/res/layout/list_item_alarm.xml
- app/src/main/res/layout/list_item_station.xml
There was an issue with some drawables - it is solved by enabling support library for drawables.
> fix #200 - return support of older android sdk >= 15

- app/src/main/res/layout/list_item_statistic.xml
+ changed the statistic page layout
+ now in two colums
> Two-columns statistic page layout

- app/src/main/aidl/net/programmierecke/radiodroid2/IPlayerService.aidl
- app/src/main/aidl/net/programmierecke/radiodroid2/data/StreamLiveInfo.aidl
- app/src/main/java/net/programmierecke/radiodroid2/ActivityPlayerInfo.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerServiceUtil.java
- app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java
- app/src/main/java/net/programmierecke/radiodroid2/data/StreamLiveInfo.java
- app/src/main/java/net/programmierecke/radiodroid2/interfaces/IStreamProxyEventReceiver.java
- app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java
I also refactored passing of Map<String, String> for live info into StreamLiveInfo class.
> Add support of lyric apps (set necessary metadata in media session), solves #129

- app/src/main/AndroidManifest.xml
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/players/ExoPlayerWrapper.java
- app/src/main/java/net/programmierecke/radiodroid2/players/MediaPlayerWrapper.java
- app/src/main/java/net/programmierecke/radiodroid2/players/PlayerWrapper.java
- app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
Open external equalizer app if select "Equalizer" in settings, if no equalizer app exists - show toast with error.
> Add support for external equalizers, solves #122

- app/src/main/res/layout/list_item_category.xml
- app/src/main/res/layout/list_item_recording.xml
- app/src/main/res/layout/list_item_statistic.xml
improved page layouts
+ statistics page
+ recordings page
+ tags page
+ countries page
+ languages page
> Improved page layouts

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
fix #187 clickable station icons; bump version 0.41
+ bump version 0.41
+ click onto station icon sets or resets station as favorite
+ new user preference for this feature
> Fix 187 clickable stations icons

- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/drawable/ic_star_transparent_with_border_24dp.xml
- app/src/main/res/layout/list_item_station.xml
This commit adds 
+ a green transparent icon with a white border
+ to all station icons of **starred** stations
> Show star icons on favorites

- app/src/main/res/drawable/ic_star_transparent_with_border_24dp.xml
improved favorite star layout:
*  using stroke-attributes
* set stroke width
* greenish transparent filling colour
* yellow transparent outline
> changed favorite-star layout

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterRadioAlarm.java
- app/src/main/res/drawable/ic_delete_white_24dp.xml
- app/src/main/res/drawable/ic_star_transparent_with_border_24dp.xml
- app/src/main/res/layout/list_item_alarm.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
add delete button for history or favorites
+ fix issue #172
> History delete button

- app/build.gradle
> bump version 0.42

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
> show delete buttons only for non-empty favorite/history lists

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/ActivityRadioStationDetail.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java
- app/src/main/java/net/programmierecke/radiodroid2/RadioDroidApp.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/RecyclerItemSwipeHelper.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/SwipeableViewHolder.java
- app/src/main/res/layout/list_item_station.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
@werman @segler-alex conflicts solved, can be merged (tested, works).
I expected, that a right-swipe removes the station item, now it is a left-swipe. Is there a general ux recommendation for assigning "left-swipe means removal" ? Just asking.
> Swipe left removes; bump version 0.43

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
+ bump version 0.44
+ fix issue #137
+ fix last view bug (don't use onSaveInstanceState but SharedPrefs)
+ start with last played stations (history view is the new default)
+ if history is selected but empty: start with all stations
+ if favorites are selected but empty: start with all stations
+ reordered list of startup actions
+ adding a fourth option "start with last view"
+ small German "about app" text changes
> bump version 0.44; new startup mechanism

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/res/menu/menu_main.xml
+ search can be done directly from these views, too
> enable search also on history and favorite view

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/FavouriteManager.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
bump version 0.45
+ add a station automatically as favorite when it is played
+ feature (default=on) has been added as a new user option
> version 0.45; auto-favorite station when played

- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
+ both swipe directions are enabled to remove the station item now
> swipe left or right to remove

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerServiceUtil.java
- build.gradle
+ fixes #71
+ supersedes https://github.com/segler-alex/RadioDroid/pull/85
+ bump version 0.46
> Stop PlayerService when unused; bump version 0.46

- app/build.gradle
- build.gradle
+ dependencies were updated
+ com.google.android.exoplayer:exoplayer:r2.5.4
(does not solve https://github.com/segler-alex/RadioDroid/issues/229 )
> updated dependencies

- app/src/main/AndroidManifest.xml
- app/src/main/aidl/net/programmierecke/radiodroid2/IPlayerService.aidl
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/ActivityPlayerInfo.java
- app/src/main/java/net/programmierecke/radiodroid2/AlarmReceiver.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayer.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerServiceUtil.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/res/drawable/ic_pause_circle.xml
- app/src/main/res/drawable/ic_play_circle.xml
- app/src/main/res/drawable/ic_start_recording.xml
- app/src/main/res/drawable/ic_stop.xml
- app/src/main/res/drawable/ic_stop_recording.xml
- app/src/main/res/layout/layout_main.xml
- app/src/main/res/layout/layout_player_status.xml
- app/src/main/res/layout/layout_timer_chooser.xml
- app/src/main/res/menu/menu_drawer.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/menu/menu_player_info.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- removed player status from the drawer.
- added a view located at the bottom of the every screen with play/pause/record controls and a current status of a playback (station, track title, location of a recorded track, etc).
- removed some unused action/elements from status page.
- simplified the interface.
- added an icon to the player and possibility to place it even in notiification.
It is not a final commit. I uploaded it now just to discuss it with you. I also need to remove unused code and to think about where to place alarm button. And how to place an image into a notification. And how to get last played radio station and add it to the player's view after start up.
What do you think?
> Added mini player at the bottom of the screen

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayer.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/res/color/menu_bottom_text_color.xml
- app/src/main/res/layout/layout_main.xml
- app/src/main/res/layout/layout_player_status.xml
- app/src/main/res/menu/menu_bottom_navigation.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/attrs_theme.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/preferences.xml
- now BottomNavigationView is a default navigation. NavigationView is here too if someone likes it more.
- so many code changes. Made it more readable & clean & awesome.
- "About" and "Statistic" were removed from menu and were placed in Settings. 
- "Recordings" button now located in the menu (for NavigationView) and in the mini player (for BottomNavigationMenu).
@segler-alex @werman @Wikinaut  what chipset your devices have? My phone is on MTK chipset and I have problems with speed of fragments. Its opens with a delay <=500ms.  Seems like list_item_station is not optimized. Do you have such problems too?
> Added BottomNavigationView

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/layout/list_item_station.xml
- app/src/main/res/layout/stub_list_item_station_details.xml
- app/src/main/res/values/strings.xml
Here I tried to make list_item_station faster than before. It happened but speed is not perfect. 
Also disabled backstack support when using BottomNavigationView (as Google suggest) but app will show alert with ability to close the app with second back button press. So user will not exit by mistake.
Fixed bugs added with previous PR:) Seems like OK now.
> Speed for list item, alert for backstack handler, fixes for bugs

- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- added missing strings. Now all strings translated.
- rearranged strings translated by @werman. Just to make ru strings located at the same place of file as en strings. Will help to find something and to maintain translation in a future.
- added player action buttons to translations (pause, resume, stop from notification).
> [RU] Translation

- app/src/main/res/layout/layout_main.xml
- app/src/main/res/layout/layout_player_status.xml
- app/src/main/res/layout/list_item_alarm.xml
- app/src/main/res/layout/list_item_station.xml
- app/src/main/res/layout/stub_list_item_station_details.xml
Added background for all buttons and list items. It shows when user presses an element. Like in every Google's app
> Material background color everywhere (on highlight)

- app/src/main/res/values-es/strings.xml
Updated spanish translation (version 0.51)
> Update strings.xml / Actualizado idioma español

- app/src/main/res/values-el/strings.xml
Hi @segler-alex 
I contribute Greek translations to various projects, from time to time.
Just finished the translation of RadioDroid.
I did a spellcheck.
The rest of mistakes will be found when (and if) the translation 
gets published in a newer version of RadioDroid.
You can check my other translation contributions at...
https://github.com/nikoss/my-translation-contributions
Have a nice day!
Nikos
> Greek translation 001

- app/src/main/res/values-el/strings.xml
> greek translation 002

- app/build.gradle
> Bump build tools to v27.0.3 - fix crashing certain custom ROMs.

- app/src/main/res/values-es/strings.xml
Review, update and complete Spanish translation
> update Spanish translation

- app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/data/ShoutcastInfo.java
- app/src/main/java/net/programmierecke/radiodroid2/proxy/ProxySettingsDialog.java
Fixes #390 and unreported crash in mpd dialog.
> Fix crash on empty port field in proxy and mpd dialogs

- app/src/main/res/layout/dialog_proxy_settings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
Deleted the restriction to show the third line when the proxy test fails
Added three option tips
Added four missing strings
Changed the default retry timeout to a more appropriate value
> A Few Adjustments

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> Added Two Missing Strings

- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/ExoPlayerWrapper.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
Resolves #131 
So far I have only tested it for situations where connection is lost because of client side problems.
> WIP: Attempt playback resume when network connection is regained

- app/build.gradle
'app_name' was both defined in gradle and strings resources.
> Fix build failure due to resource name collision

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Modified some strings in proxy and favorites setting
> Modified Strings in Proxy and Favorites

- README.md
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Made all elements in README.md centered
Modified strings about Wi-Fi
> Modified README.md & Minor String Changes

- app/src/main/res/values-in/strings.xml
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)
> Add IN (Indonesian) translation

- app/src/main/res/values-pl/strings.xml
Deleted some untranslatable strings
> Fixed Some String Errors in values-pl

- app/src/main/res/values-in/strings.xml
> Reviewed Strings in values-in

- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
Listen to ACTION_MEDIA_BUTTON intents that android sends when it
restarts the last active media session.
> Respond to media buttons when restarted

- app/src/main/res/values-zh-rCN/strings.xml
> Added New Strings

- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayer.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
> Add auto-play on startup option

- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
* current radio station name (as album name)
* radio station icon
Should fix #462
> Provide more metadata for Bluetooth devices

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
1 - Deleted some extra periods in strings
2 - Moved **Auto-play** from **General** to **Player**
3 - Disabled **Use circular icons** when **Show station icons** is disabled
> Option Adjustment & New Dependency

- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/recording/RecordingsManager.java
> Make parent dirs of DIRECTORY_MUSIC and Recordings if necessary

- app/src/main/java/net/programmierecke/radiodroid2/AlarmReceiver.java
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Added translatable parameters & new strings
> Made Alarm Notification Translatable

- README.md
Added GPLv3 logo & link to README.md
> Added GPLv3 Logo & Link

- app/src/main/res/values-da/strings.xml
Pull reqest for danish translation (not complete)
> Danish translation

- app/src/main/res/values-da/strings.xml
Deleted some untranslatable strings
> Fixed Some String Errors in values-da

- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/RecyclerItemMoveAndSwipeHelper.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/RecyclerItemSwipeHelper.java
… using the standard long press drag and move callbacks from ItemTouchHelper.SimpleCallback
> Make favourites rearrangeable via drag and drop

- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/RecyclerItemMoveAndSwipeHelper.java
* fix unchecked warnings
* shorten SaveManager.move
Thanks to @werman
> Improve rearrangeable favourites code

- app/src/main/res/values-da/strings.xml
Still not finish but getting there slowly
> Update Danish strings.xml (#1)

- app/src/main/java/net/programmierecke/radiodroid2/views/IntEditTextPreference.java
Fixes: 4192f6d19da35024ce950ec410f644b5b8c226b5
Fixes: #490
> Fix reading initial value for IntEditTextPreference

- app/src/main/res/values-zh-rCN/strings.xml
Added toggle view to values-zh-rCN
> Added New String to values-zh-rCN

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
When listening to radio almost asleep you don't want to fiddle arround
with a seekbar every time. Particularly not with a default value of one
minute :)
> Remember previous sleep timer setting

- app/src/main/java/net/programmierecke/radiodroid2/FragmentAlarm.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterRadioAlarm.java
Fixes #503
Let's switch to a RecyclerView later.
> Refresh alarms listview after an alarm is deleted

- app/src/main/AndroidManifest.xml
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/MediaSessionCallback.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/drawable-anydpi/ic_back_arrow_24dp.xml
- app/src/main/res/layout/stub_list_item_station_details.xml
- app/src/main/res/values/strings.xml
> Add possibility to create "pinned" station shortcuts on home screen

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Simplified string in values
Added new string to values-zh-rCN
> Simplified & Added New String

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/FavouriteManager.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/data/DataRadioStation.java
* also improve the look of the shortcut icons also for pinned shortcuts
* use picasso transforms for circle and rounded-corner homescreen icons
* improve code by using callbacks
https://youtu.be/cX9FYWTpmXQ
> Create dynamic (long press launcher) shortcuts from favorites

- app/src/main/java/net/programmierecke/radiodroid2/FavouriteManager.java
- app/src/main/java/net/programmierecke/radiodroid2/data/DataRadioStation.java
> Fix typos and indent in dynamic shortcuts pr

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/ActivityRadioStationDetail.java
- app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java
- app/src/main/res/drawable-anydpi/ic_access_alarms_black_24dp.xml
- app/src/main/res/drawable-anydpi/ic_hourglass_empty_black_24dp.xml
- app/src/main/res/layout/stub_list_item_station_details.xml
- app/src/main/res/menu/menu_bottom_navigation.xml
- app/src/main/res/menu/menu_drawer.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/menu/menu_station_detail.xml
Before, pretty much everything was mixed up.
This might partially resolve some confusions (#27, #64)
> Fix icons, names, ids for access alarms, add alarm, set sleep timer

- app/src/main/res/values-da/strings.xml
Update, review and some misspelling.
> Update Danish strings.xml

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentAlarm.java
- app/src/main/res/menu/menu_main.xml
* using a new entry in the main menu
* picking the last played station
* fixes #64
> Allow adding alarms from alarm fragment

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/MediaSessionCallback.java
- app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/RadioDroidBrowser.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/data/StreamLiveInfo.java
Can be tested with:
https://github.com/morckx/android-media-controller/tree/dont-tint-mediaitem-icons
> Improve media session compliance

- app/src/main/java/net/programmierecke/radiodroid2/RadioDroidBrowser.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/data/DataRadioStation.java
> Fix empty icon urls crash on dynamic shortcut creation

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
1 - Fixed a string error in values
2 - Added new strings to values-zh-rCN
> Fixed Error & Added New Strings

- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/IcyDataSource.java
> Guess stream content type based on url extension if not provided

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
1 - Added some missing strings of searchpreference
2 - Moved **radio browser server** to the bottom
> Added Missing Strings & Reorganized Settings Item

- app/src/main/res/values-pl/strings.xml
Hey,
Please update the translation.
Thanks
> Update the translation

- app/src/main/res/values-pl/strings.xml
Deleted two untranslatable strings
> Fixed String Error in values-pl

- app/src/main/res/values-ca/strings.xml
Thanks to @bluegeekgh, from/fixes #554
> Add Catalan translations

- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/data/DataRadioStation.java
> Automatically add missing uuids while loading station lists

- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java
- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
Done by making downloading be part of PrePlaying phase and including
PrePlaying in RadioPlayer.isPlaying().
The url retrieval is still quite ugly and isn't easily cancelled (no way to cancel underlying http call at the moment).
Closes: #571
> Make possible to pause when downloading real station url

- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
> Fix crash when trying to play previous or next station without current

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
1 - Added new strings to values-zh-rCN.
2 - Deleted some extra blanks in values.
> Added New Strings to values-zh-rCN

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/alarm/FragmentAlarm.java
- app/src/main/java/net/programmierecke/radiodroid2/alarm/ItemAdapterRadioAlarm.java
- app/src/main/java/net/programmierecke/radiodroid2/alarm/RadioAlarmManager.java
> Fix alarm's list refreshment issues

- app/src/main/res/values-es/strings.xml
Update and complete Spanish translation
> Update and complete Spanish translation

- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerSmall.java
Also remove unnecessary icon updates.
Closes: #582
> Show launcher icon in small player when no station was played before

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
> Fix fragments handling after activity recreation

- app/src/main/res/values-es/strings.xml
1 - Deleted two untranslatable strings.
2 - Deleted some extra blanks.
> Fixed String Errors in values-es

- app/src/main/res/values-de/strings.xml
I amended some of the German strings because they were not well crafted.
> updated some German text strings

- app/src/main/res/xml/preferences.xml
I moved the autoplay-setting to the interaction menu
+ also set the default value to "true"
> moved the start-autoplay setting from player menu to interaction menu

- app/src/main/res/xml/preferences.xml
1 - There have been many items in **interaction**.
2 - **Auto-play** should not be enabled by default.
> Reversed #590

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
1 - Simplified 3 strings in values.
2 - Added 3 new strings to values-zh-rCN.
> Simplified & Added New Strings

- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
1 - Deleted two untranslatable strings.
2 - Deleted some extra blanks.
> Fixed String Errors in values-da

- app/src/main/AndroidManifest.xml
> Allow backups; fixes #587

- app/src/main/res/values-de/strings.xml
Two more German string changes
> chg German strings re. reconnection and giving up

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentBase.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentTabs.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/station/DataRadioStation.java
- app/src/main/java/net/programmierecke/radiodroid2/station/FragmentStations.java
- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterIconOnlyStation.java
- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/station/StationsFilter.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/CustomFilter.java
- app/src/main/res/layout/fragment_stations_remote.xml
I tested https://github.com/werman/RadioDroid/commit/6a55b03c3a0e21b1e2cd2dbc0ffa68b1e74ed6f2 and propose to merge this.
Fixes https://github.com/segler-alex/RadioDroid/issues/309
> Show stations during search as query being typed

- app/src/main/aidl/net/programmierecke/radiodroid2/IPlayerService.aidl
- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/players/PlayerWrapper.java
- app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java
- app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/ExoPlayerWrapper.java
- app/src/main/java/net/programmierecke/radiodroid2/players/mediaplayer/MediaPlayerWrapper.java
- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerServiceUtil.java
Notable case is phone calls which will force playback pause and will
pause the application to show phone UI.
See #610
> Resume playback after a phone call ended

- app/src/main/java/net/programmierecke/radiodroid2/service/BecomingNoisyReceiver.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
> Add preference to continue playback when headset disconnects

- app/src/main/aidl/net/programmierecke/radiodroid2/players/PlayState.aidl
- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerFull.java
- app/src/main/java/net/programmierecke/radiodroid2/players/PlayState.java
- app/src/main/java/net/programmierecke/radiodroid2/station/live/metadata/TrackMetadataCallback.java
- app/src/main/java/net/programmierecke/radiodroid2/station/live/metadata/lastfm/LfmMetadataSearcher.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/RateLimiter.java
- Introduce better rate limit;
- Do not do unnecessary calls to fetchTrackMetadata
@segler-alex Also add missed files to fix broken build. Sorry Android Studio had some troubles with git and I missed it...
> Improve album art fetching

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
> Fix stations searching with drawer layout

- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
> Fix drag and drop in favourites

- app/src/main/java/net/programmierecke/radiodroid2/FragmentTabs.java
- app/src/main/java/net/programmierecke/radiodroid2/station/FragmentStations.java
Fixes: 6a55b03c3a0e21b1e2cd2dbc0ffa68b1e74ed6f2
Closes: #651
Closes: #649
> Fix FragmentStations crash on rotation

- app/src/main/res/layout/layout_main.xml
RecyclerViews did not recycler their elements in history and favourites.
> Fix recycling of elements in RecyclerViews for station lists

- app/src/main/AndroidManifest.xml
> Fix RadioDroidBrowserService package name in AndroidManifest

- app/build.gradle
- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
Updated com.google.android.material:material for Snackbar.setAnchorView
Closes: #650
> Fix UNDO snackbar positioning

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/players/mpd/MPDServersRepository.java
* changed code to get mpd server list from mpdclient
> get server list from mpdclient

- app/src/main/java/net/programmierecke/radiodroid2/RadioBrowserServerManager.java
- app/src/main/java/net/programmierecke/radiodroid2/RadioDroidApp.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/Tls12SocketFactory.java
> testing fix

- app/build.gradle
- app/src/free/java/net/programmierecke/radiodroid2/GoogleProviderHelper.java
- app/src/main/java/net/programmierecke/radiodroid2/RadioDroidApp.java
- app/src/play/java/net/programmierecke/radiodroid2/GoogleProviderHelper.java
this tries to upgrade TLS on devices with google
> install google helper for tls upgrade in play version

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
This fixes rare crash when mFragmentManager is null when handling
new intent.
Activity.onNewIntent documentation:
```
An activity can never receive a new intent in the resumed state.
You can count on onResume() being called after this method,
though not necessarily immediately after the completion this callback.
If the activity was resumed, it will be paused and new intent will be
delivered, followed by onResume().
If the activity wasn't in the resumed state, then new intent can be
delivered immediately, with onResume() called sometime later when
activity becomes active again.
```
> Handle intents in onResume ensuring that activity is initialized

- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerFull.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerSmall.java
- app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayerSelectorAdapter.java
Thus retaining notification which would be expected by user.
Closes: #682
> Pause playback instead of stopping it when user press pause button in ui

- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-nn/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
Deleted radio browser server strings
> Deleted Unused Strings

- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
Fixes: cb9981db68b8af66756d386e93a99d954e9e4fb0
> Make notification dismissible when state is PlayState.Idle

- app/src/main/java/net/programmierecke/radiodroid2/history/TrackHistoryAdapter.java
- app/src/main/java/net/programmierecke/radiodroid2/history/TrackHistoryInfoDialog.java
- app/src/main/res/values/styles.xml
Also extracted dialog specific code from TrackHistoryAdapter into
TrackHistoryInfoDialog for it to extend BottomSheetDialogFragment
in order to fix its styling.
Closes: #702
> Fix styling of bottom sheet dialogs

- app/src/main/res/values/styles.xml
> Fix menu text color for theme changes

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Seems to work, but could use some more testing.
> Update libraries and gradle

- app/src/main/AndroidManifest.xml
- app/src/main/java/net/programmierecke/radiodroid2/service/RadioDroidBrowserService.java
Fixes: #725
Fixes: #724
@morckx This should fix it
> Disable RadioDroidBrowserService because it is not ready for usage

- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java
> Fix missing icons in station item dropdown menu

- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerFull.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerSmall.java
- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
- app/src/main/java/net/programmierecke/radiodroid2/service/RadioDroidBrowser.java
- app/src/main/java/net/programmierecke/radiodroid2/station/DataRadioStation.java
- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterIconOnlyStation.java
- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java
Upon deserializing we now normalize IconUrl value to be able to
check for its absence with simple TextUtils.isEmpty
Also did some fixups of cases when we don't have the icon.
> Add .hasIcon method to DataRadioStation to unify url check

- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
Service shouldn't call directly or indirectly itself via
PlayerServiceUtil since it requires service to be bound which may happen
after onStartCommand is called.
The fix is not pretty, but to do it in a better way we must get rid
of aidl and all indirection it brings.
Closes: #730
@morckx It's a bit more verbose than your fix, but I believe this a more right solution. However the spaghetti around the player service is getting out of had...
It fixes the issue on emulator, but I'd like your confirmation.
> Fix playback not starting when service is started with media button

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java
Fixes #729 
Iconics 4.0.1 -> 4.0.2 was the culprit. 
@werman : please have a look if it works.
> Fix missing icons 2

- app/src/main/java/net/programmierecke/radiodroid2/history/TrackHistoryInfoDialog.java
- app/src/main/res/values/strings.xml
> Ask user before redirecting to QuickLyric's page in a market

- app/src/main/java/net/programmierecke/radiodroid2/RadioBrowserServerManager.java
> ignore all.api server

- app/src/main/java/net/programmierecke/radiodroid2/RadioBrowserServerManager.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
Fixes: d6e1a225cf981877c94cf9714da070ce63f5b7aa
Fixes: 4aadd2dbc7861e5762ce517331edde2b5e1ae9ea
> Fix string comparisons (use .equals)

- app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java
- app/src/main/java/net/programmierecke/radiodroid2/RadioBrowserServerManager.java
- app/src/main/res/values/strings.xml
> added export history

- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/station/StationActions.java
> Fix crash when voting for station when offline

- app/src/main/res/layout/list_item_history_track_item.xml
> Fix track history UI when station icons are disabled

- app/src/main/res/menu/menu_player.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
1 - deleted the extra share command from the menu.
2 - changed history to track history.
> Full-screen Player UI String Adjustments

- app/src/main/java/net/programmierecke/radiodroid2/alarm/FragmentAlarm.java
- app/src/main/java/net/programmierecke/radiodroid2/alarm/TimePickerFragment.java
> Show previously picked time when editing alarm's time

- app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerFull.java
> Fix state updating of record button

- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Made playlist load and save notifications translatable.
> Made Playlist Load & Save Notifications Translatable

- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterIconOnlyStation.java
- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/RecyclerItemMoveAndSwipeHelper.java
- app/src/main/java/net/programmierecke/radiodroid2/utils/RecyclerItemSwipeHelper.java
- app/src/main/res/values/attrs_theme.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
Taken from
https://medium.com/@zackcosborn/step-by-step-recyclerview-swipe-to-delete-and-undo-7bbae1fce27e
Thanks also to Marcel Jurišta for the modificaftion:
https://medium.com/@juristamrcl/great-article-thank-you-69b558414dbd#--responses
and to Ameel Beesony for completing it.
This should prevent accidental removal of favorites, unless without looking.
> Add trash can background to swipe to delete

- app/src/main/AndroidManifest.xml
- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
This should fix #807, but requires some testing. 
Maybe the problem is just moved to another place.
> Use JobIntentService instead of IntentService for PlayerService 

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-nn/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-tr/strings.xml
Fixed string errors in some languages
> Fixed String Errors in Some Languages

- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Simplified & added context menu strings
> Simplified & Added Context Menu Strings

- app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
> Play audio warnings as music and not as alarm stream

- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
Added two new strings to da, es, zh-rCN
> Added New Strings to da, es, zh-rCN

- app/src/main/res/values-in/strings.xml
Deleted four untranslatable strings.
> Fixed String Errors in values-in

- app/src/main/java/net/programmierecke/radiodroid2/station/StationPopupMenu.kt
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> typo fix context_menu_play_in_radiodrid

- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java
Fixing typo from 8484229b6fa0d577465505dbd7aadf1ef6c80fc9
> Fix bookmarking and adding to home screen in station details

- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
Found while running UI automation tests.
> Fix ConcurrentModificationException while refreshing stations' IDs

- app/src/main/res/values-pt-rBR/strings.xml
Added pt-rBR strings
Close: #877
> Added pt-rBR Strings

- app/src/main/java/net/programmierecke/radiodroid2/FragmentTabs.java
This makes it easier to change the list of tabs in the future and avoids errors with mixing up indices.
Also fix typo in "addresses"
> Use constants for tab-index

- app/src/main/res/values-zh-rCN/strings.xml
> Added String to CN

- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
- app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
- app/src/main/java/net/programmierecke/radiodroid2/Utils.java
- app/src/main/java/net/programmierecke/radiodroid2/station/DataRadioStation.java
- app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java
- app/src/main/res/layout/fragment_stations.xml
- app/src/main/res/values/strings.xml
I added a refresh feature to the history and the favorites tab.
It should get rid of stations that are not in the database anymore and also does update entries from the webservice.
> add refresh on history and favorites tab

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> Added Strings to CN

- app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
- app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java
Made the notification last longer
> Made Notification Last Longer

- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
1 - Added some missing strings to FR
2 - Fine adjustments to EN & CN
> Strings Amendments

- app/src/main/java/net/programmierecke/radiodroid2/players/PlayStationTask.java
> Reverted "Fix choice of external audio players (#827)"

- app/src/main/res/values-eu/string.xml
I request you to add the Basque language (eu). This is a great app. Thank you.
> Add basque (eu) language

- app/src/main/res/values-gl/strings.xml
New language for RadioDroid, first galician (gl) translation
Novo idioma engadido para a interface de RadioDroid: galego!
> create gl strings.xml
