app/src/main/res/layout/layout_player_status.xml, app/src/main/res/layout/list_item_alarm.xml, app/src/main/res/layout/list_item_station.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values/strings.xml
This is mainly useful to visually disabled users relying on assistive technologies.
I have tested this on Android 6.0.1, however setting contentDescription is supported since android 1.6 so this is risk free as far as RadioDroid compatibility is concerned.
For me this is working as intended. Visually disabled or blind people in general like to play online radio, so by accepting this you are doing great service to me and other people who may benefit.
=> Provide text alternatives for image only buttons increasing overal app accessibility

app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java, app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java
PlayerService: Replay current stream instead of stopping in case of proxy problems
StreamProxy: Increase buffer, read timeout
more detailed logging
About the changes: These are mainly changes that affect the way that radiodroid behaves
when being used with bad (or varying) internet connection.
Currently, radio droid is Playerservice is being stopped if the proxy has for example a streaming error
or bad connection. That means that you have to manually restart the stream each time
this happens. This is very undesirable - you have to pull the smartphone out and act every time.
With this change, instead it tries to restart streaming by itself. No manual intervention needed.
Stopping a stream manually works as usual.
The increased buffer also improves playback quality, however, it is not …
=> proxy - do not stop on error; increase buffer & timeout

app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Add an option to display Starred Stations at application startup
Look at the shared pref on MainActivity onResume and pick the right Fragment to display accordingly
When using RadioDroid, I realized I was systematically going to starred radios panel as soon as the app was started. I thought maybe the app could do that for me.
=> Add setting to display Starred Radio at startup

app/src/main/res/layout/list_item_alarm.xml
**reason:** Removing the "clickable flag" on the textview "alarm time" which causes the app to break on click.
**explanation**: i tried to add  the onClickListener with the TimePicker only to the textview holding the alarm time. I forgot to remove the flag. Sorry
=> fix exception on clicking alarm

app/src/main/res/layout/list_item_station.xml
The button which calls menu for a station had too small size which cause accidental play of the station.
=> Fix pressing station's 'more' button plays it.

app/src/main/java/net/programmierecke/radiodroid2/HistoryManager.java
At the moment history manager stores duplicates which I think isn't a useful behaviour. I propose to store only unique stations and move last played ones to the top of the list.
=> Make history manager store station chronologically and without duplicates

app/src/main/aidl/net/programmierecke/radiodroid2/IPlayerService.aidl, app/src/main/java/net/programmierecke/radiodroid2/AlarmReceiver.java, app/src/main/java/net/programmierecke/radiodroid2/BecomingNoisyReceiver.java, app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java, app/src/main/java/net/programmierecke/radiodroid2/PlayerServiceUtil.java, app/src/main/java/net/programmierecke/radiodroid2/StreamProxy.java, app/src/main/java/net/programmierecke/radiodroid2/Utils.java, app/src/main/java/net/programmierecke/radiodroid2/players/ExoPlayerWrapper.java, app/src/main/java/net/programmierecke/radiodroid2/players/MediaPlayerWrapper.java, app/src/main/java/net/programmierecke/radiodroid2/players/PlayerWrapper.java, app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java, app/src/main/res/drawable/ic_pause_24dp.xml, app/src/main/res/values/strings.xml
This changes a lot in PlayerService. Should fix: #87 #92, but without auto play when device is connected and issue #73.
I added pause and resume of stations playing which is utilized by notification UI and media button.
Now when e.g. bluetooth headset disconnected play will pause which is desired behavior for media player. Also player will reduce volume if any short sound, like notification, will appear.
I had to refactor PlayerService because it was hard maintain it with new changes.
There were several issues:
- Never ended thread with looper which was used for exo player.
- Spawning new threads for small tasks.
- Too many different layers of logic were in PlayerService like controlling two diferrent players, controlling proxy, updating notifications and so on. Which with new logic was …
=> Refactor PlayerService. Add media button support. Add pause/resume. Other small improvements

app/src/main/AndroidManifest.xml, app/src/main/java/net/programmierecke/radiodroid2/Utils.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
As this will use the mobile data connection. Added a preference to enable/disable this behavior. The check is done when actually starting to play to allow to browse/bookmark/manage/.. and only warn when playing actually starts.
It also plays a short sound to get the attention of the user, but this can easily removed if you don't want to have this.
Closes #124
=> Allow to warn when no wifi connection is available

app/src/main/res/values-de/strings.xml
3 German translations were missing and English strings were displayed.
=> Added missing German translations for settings

app/src/main/java/net/programmierecke/radiodroid2/Utils.java
Bugfix for simple bug. When playing natively and switching to chromec…ast, native replay keeps playing in parallel to chromecast.
To trigger the bug:
* Play a radio station natively
* Choose chromecast device for playback
* The native playback continues
* Select a radio station
* Chromecast playback starts in parallel to native replay
Successfully tested the bugfix on a Chromecast setup.
=> Bugfix for switching from native replay to chromecast while playing.

.gitignore, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
These changes are needed when building with the latest toolchain. Today AndroidStudio3 was published.
See also https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html .
Tested. Works.
=> updated for AndroidStudio 3 and gradle 4.1

app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java
+ scroll to top on history screen when a station is played
+ because the played station is always on top of the history list
=> fix issue #211

app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java, app/src/main/java/net/programmierecke/radiodroid2/Utils.java, app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java, app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/ExoPlayerWrapper.java, app/src/main/java/net/programmierecke/radiodroid2/players/mediaplayer/MediaPlayerWrapper.java, app/src/main/java/net/programmierecke/radiodroid2/players/mediaplayer/StreamProxy.java, app/src/main/java/net/programmierecke/radiodroid2/recording/Recordable.java, app/src/main/java/net/programmierecke/radiodroid2/recording/RecordingsManager.java, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Now there is an option with predefined name formats for recordings. By default the first option is selected (the most verbose one). Fixes regression #273 
I have decided to make format selection localized. Also the delimiter between name parts is '+' because usage of underscores makes a salad from words in a file name (in my opinion).
Ultimately there should be a user input for format but I've got lazy.
=> Add option to change recording's file name format. Fix #273

app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java
Force to call onDetachedFromRecyclerView for adapter when view which use it being destroyed. Without this onDetachedFromRecyclerView may be not called in some situations.
=> Fix leaking intent receiver in ItemAdapterStation. Fix #290

app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayer.java, app/src/main/java/net/programmierecke/radiodroid2/MPDClient.java, app/src/main/java/net/programmierecke/radiodroid2/recording/RecordingsManager.java, app/src/main/res/drawable/ic_start_recording.xml, app/src/main/res/values/colors.xml
- added red color for station name textView while user is recording a station. Suggested here: #291 but it looks different. Icon at the left side of the name (as suggested) will make a code less maintainable (xml layout and java file should be changed hard).
- timeout for local MPD servers now equals to 0.5 sec and 3 sec for remote servers. This will help to prevent long time waiting for connection while some of the servers are not reachable. 
- recordings are sorted by date
=> Red color for station name while recording a station and MPD timeout

app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java, app/src/main/java/net/programmierecke/radiodroid2/MPDClient.java
The end solution should be a refactor of MPDClient, maybe use some library to handle mpd. At the moment code is pretty messy.
Remove unnecessary creation of HistoryManager and FavouriteManager in ActivityMain.
Reformat corresponding files.
=> Fix memory leak of ActivityMain caused by MPDClient's thread. #306

app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java, app/src/main/java/net/programmierecke/radiodroid2/MPDClient.java, app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java, app/src/main/java/net/programmierecke/radiodroid2/data/DataRadioStation.java, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
- favorites and history were empty after one of the previous commits. Fixed
- NPE when switching between tabs. Fixed
- expanded comments in MDPClient and made timeout equals to 1 second
- made click trend icon hideable
closes #305 #317
=> Empty favorites, click trend icon and NPE

app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayer.java, app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterRadioAlarm.java, app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java, app/src/main/res/layout/layout_player_status.xml, app/src/main/res/values/strings.xml
Since I have last looked at the accessibility shortcomings of the app, many things got redesigned. Part of the redesign are some buttons which became multi purpose e.g. recording button is working as Record and Stop recording button, Play / Pause, Star / Unstar and similar. I have added one missing contentDescription and dynamically set contentDescription in code at all the places where the imageResource is changed.
I think this all is usefull to screen reader users.
I've tested all these changes on Nokia 6 running Android 8.1.0 and Samsung Galaxy S 7 running Android 7.0.
=> A11y: Dynamic content descriptions

app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java, app/src/main/res/values/strings.xml
Add content description for the click trend icon in the list of stations. Disabling the icon from showing also causes assistive tools
not to report this content description.
It would be awesome to get the strings refined by the native english speaker I think but functionally it's working great.
Hopefully now all the usefull buttons and icons are exposed to screen reader users.
=> A11y: Add content description for the click trend icon

app/src/main/java/net/programmierecke/radiodroid2/ActivityRadioStationDetail.java, app/src/main/java/net/programmierecke/radiodroid2/AlarmReceiver.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentBase.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayer.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentServerInfo.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentStations.java, app/src/main/java/net/programmierecke/radiodroid2/RadioDroidApp.java, app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java, app/src/main/java/net/programmierecke/radiodroid2/Utils.java, app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java, app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java, app/src/main/java/net/programmierecke/radiodroid2/proxy/ProxySettings.java, app/src/main/java/net/programmierecke/radiodroid2/proxy/ProxySettingsDialog.java, app/src/main/res/layout/dialog_proxy_settings.xml, app/src/main/res/layout/layout_server_alert.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Supported proxies are: HTTP and SOCKS5.
SOCKS4 proxies aren't supported because OkHttp doesn't support them because Android has [issues](https://github.com/square/okhttp/issues/1359) with SOCKS4.
All http requests now made through OkHttp.
All OkHttp instances now share same thread pool.
I have tested this with public proxies and with Orbot. Orbot has [issues](https://github.com/n8fr8/orbot/issues/159) with http proxy but SOCKS works. I haven't tested proxy auth but it should work according to OkHttp documentation.
=>  Add support for proxies

app/src/main/res/menu/menu_bottom_navigation.xml
Bottom navigation menu is configured not to show text at all times. Therefore also provide contentDescriptions for those menu items
to make sure screen reader users have something to hear whenever no
titles are showing alongside the icons.
=> a11y: content descriptions for the bottom menu nav items

app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
Set notification visibility to public thus allowing notification to be shown when "Hide sensitive notification content" option is enabled.
Fixes #363
=> Mark notification as non-sensitive

app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/res/values/styles.xml
SaveFileDialog now uses current application theme.
Apply theme colors on MaterialEditText's custom color attributes.
Fixes #364
=> Fix theming of file playlist's load/save dialog

app/src/main/AndroidManifest.xml, app/src/main/java/net/programmierecke/radiodroid2/FragmentRecordings.java, app/src/main/res/xml/file_paths.xml
Since target sdk is >= 24 - FileProvider should be used to make records
accessible for other apps.
For versions between JELLY_BEAN and LOLLIPOP ClipData workaround is required.
See more at https://commonsware.com/blog/2016/08/31/granting-permissions-uri-intent-extra.html
For lower APIs permissions are just granted for everyone.
Fixes #377 and the same issue reported in comment of #360
=> Fix crash on record opening

app/src/main/AndroidManifest.xml
The feature is still in progress however it was automatically treated
as Android Auto app which prevent it from passing review.
Should fix #389
=> Prevent RadioDroid from being submitted as Android Auto app

app/src/main/java/net/programmierecke/radiodroid2/Utils.java
Using domain resulted in attempt to resolve it via DNS in main thread
which resulted in NetworkOnMainThreadException.
Use InetSocketAddress.createUnresolved instead.
Fixes #419
=> Fix crash when using domain as host name for proxy

app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/ExoPlayerWrapper.java
The key in preferences.xml is "settings_resume_within" and not
"resume_within".  Because of that, the settings value was ignored and
the default value of 60s was always used.
=> Fix "resume within" setting not being used

app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java
Some radio stations seem to send time stamps or unchanged data every
second. So don't waste battery on updating metadata and notifications if
nothing relevant has happened and don't reset the start time either.
Fixes #464 largely.
=> Update notification only on icy title changes

app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayer.java
If no context is defined in onActivityStarted yet, auto-play will be
considered later in onActivityCreated.
Fixes #468
=> Fix auto-play-on-start related NPE

app/src/main/java/net/programmierecke/radiodroid2/PlayerService.java, app/src/main/java/net/programmierecke/radiodroid2/PlayerServiceUtil.java
Otherwise the icon of the previous station stays displayed.
Fixes #470
=> Always use a fallback icon if no station icon is configured

app/src/main/java/net/programmierecke/radiodroid2/views/IntEditTextPreference.java
Without this the fallback value will always be -1 instead of the
default.
Taken from 9663bf6268de448e749a1cb95e4a726eefd680cd
=> Fix integer preferences

app/src/main/res/values-sw360dp-v13/values-preference.xml
See
https://stackoverflow.com/questions/51518758/preferencefragmentcompat-has-padding-on-preferencecategory-that-i-cant-get-rid
Fixes #491
=> Get rid of left padding in preferences (fixes #491)

app/build.gradle
Fixes primary color in settings not correctly applied in dark mode after
recreate, resulting in black on dark grey text.
See
https://stackoverflow.com/questions/53921023/preferencefragmentcompat-wont-change-color-when-change-theme-and-recreate-activ
(To test this, toggle "Use circular icons" or "Bottom navigation" in
dark mode.)
=> Upgrade androidx preference library to 1.1.0-alpha05

app/build.gradle, app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentSettings.java, app/src/main/java/net/programmierecke/radiodroid2/RadioDroidApp.java, app/src/main/java/net/programmierecke/radiodroid2/Utils.java, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-in/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-nn/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, build.gradle
Fixes #507
Everything seems to work now, including search and back logic.
In a second PR we could re-organize a bit more, maybe.:
* add new sub-screen startup-up, including start-action and auto-play on start
* move MPD to connectivity
* move off-wifi-warning to connectivity
=> Redesign settings layout

app/src/main/res/values-da/strings.xml
settings_record_name_formatting_default_display was defined multiply,
some other strings were identical to the English original
=> Fix Danish translations build error

app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/ExoPlayerWrapper.java
Fixes #475 - at least to the extent that the behavior is the same as in the last stable release v0.69.
=> Respect warn_no_wifi setting when resuming after connection regain

app/src/main/java/net/programmierecke/radiodroid2/alarm/RadioAlarmManager.java
Currently the [`setExactAndAllowWhileIdle()`](https://developer.android.com/reference/android/app/AlarmManager.html#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent)) method is used to set alarm times. However, this does not show that there is an upcoming alarm in the system UI.
[`setAlarmClock()`](https://developer.android.com/reference/android/app/AlarmManager.html#setAlarmClock(android.app.AlarmManager.AlarmClockInfo,%20android.app.PendingIntent)) is the same as `setExactAndAllowWhileIdle()` with the added extra of showing that there is an upcoming alarm set. Upcoming alarms are shown in the status bar and on the lock screen.
=> Use alarmMgr.setAlarmClock API for system to show upcoming alarms

app/src/main/java/net/programmierecke/radiodroid2/alarm/AlarmReceiver.java, app/src/main/res/values/strings.xml
Partly fixes https://github.com/segler-alex/RadioDroid/issues/393
If the user has no internet connection when the alarm goes off, currently the alarm will fail silently.
This PR will fallback to the default system alarm sound if the radio station fails to load.
=> Alarm clock play system alarm if radio station fails to load

app/src/main/res/layout/layout_main.xml
It was a regression introduced when I updated the libraries in 8ccb828.
Now it needs to be explicitly specified that selected item should push
other aside in BottomNavigationView.
In some cases it still may not be enough to fit the text but it doesn't
happen at the moment so nothing more is needed to be done. Otherwise
it will be necessary to make the TextViews to auto resize the text.
Closes: #607
Fixes: 8ccb828
@Wikinaut Could you check it?
=> Fix long text being truncated in BottomNavigationView

app/src/main/res/values-de/strings.xml
German Apps widely use the word "Abbrechen". I never saw "Stornieren" in an App.
=> chg German string "Stornieren" to "Abbrechen"

app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/IcyDataSource.java
Happened to me once, better be safe.
=> Fix rare crash when responseBody is null in IcyDataSource.readInternal

app/build.gradle
The latest OkHttps versions which support Android 4.X are 3.12.*
See https://developer.squareup.com/blog/okhttp-3-13-requires-android-5
Reported in #642
Fixes: 0afe8b8509eb7792d14e5aede08b209873144d85
=> Fix crash on Android 4.X by downgrading OkHttp

app/src/main/aidl/net/programmierecke/radiodroid2/IPlayerService.aidl, app/src/main/aidl/net/programmierecke/radiodroid2/players/selector/PlayerType.aidl, app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentBase.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentServerInfo.java, app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java, app/src/main/java/net/programmierecke/radiodroid2/Utils.java, app/src/main/java/net/programmierecke/radiodroid2/players/RadioPlayer.java, app/src/main/java/net/programmierecke/radiodroid2/players/mpd/MPDServerData.java, app/src/main/java/net/programmierecke/radiodroid2/players/mpd/MPDServersAdapter.java, app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayStationTask.java, app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayerSelectorAdapter.java, app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayerSelectorDialog.java, app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayerType.java, app/src/main/java/net/programmierecke/radiodroid2/service/ConnectivityChecker.java, app/src/main/java/net/programmierecke/radiodroid2/service/HeadsetConnectionReceiver.java, app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java, app/src/main/java/net/programmierecke/radiodroid2/service/PlayerServiceUtil.java, app/src/main/java/net/programmierecke/radiodroid2/station/StationActions.java, app/src/main/res/values/strings.xml
- Now metered connection alert dialog will be dismissed if playback is started from other place rather than its "OK" button
- Renamed and slightly refactored `MPDServersDialog` because it's not mpd specific.
- Fixed metered warning with external player.
- Resuming after metered connection warning via media buttons are not reliable since sometimes we receive `Pause` event when playback is paused, instead of receiving `Play` event. However it's better than nothing.
=> Fix metered connection warning. Refactor server selection dialog.

app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java, app/src/main/java/net/programmierecke/radiodroid2/service/PlayerServiceUtil.java
This will fix #634 and #619. From discussions on stackoverflow it seams that the crash still would happen in extremely rare cases when system fails to call onStartCommand in 5 seconds after calling onCreate but we can ignore this.
Now resuming playback when our app had the last mediasession will actually work.
=> Fix crash when service is started by external forces and show notification if possible

app/src/main/java/net/programmierecke/radiodroid2/service/PauseReason.java, app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java
This should complete the adaptation to otherwise usual play/pause behaviour.
If you listen to RadioDroid and start a YouTube clip in between, you can simply continue listening to RadioDroid afterwards by using the notification.
=> Pause instead of stop on focus loss

app/src/main/res/values-de/strings.xml
a first approach to add reasonable German translations. See also #698 (closed).
=> +missing German strings for reconnection behaviour

app/src/main/res/values/styles.xml
On API 16, the actionbar menu background stayed white also in dark mode,
resulting in white on white print, since fb9ed131a0186885412b90e2d3d5766172774449. This patch ensures that the menu background is changed on theme changes.
=> Fix menu background color in lower APIs

app/src/main/java/net/programmierecke/radiodroid2/service/BecomingNoisyReceiver.java
MediaSession now is running while playback is paused and ACTION_AUDIO_BECOMING_NOISY
could be received in paused state. However we do not want to change pause reason.
This fixes unexpected resumes of playback when headset is reconnected.
=> BecomingNoisyReceiver: Do not pause playback if it is already paused

app/build.gradle
It should not, but does break API 16 compatibility.
This reverts commit f931e70235da236bd723b34d1e3c244756feeed7.
=> Revert "Update okhttp to 3.12.9"

app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerFull.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerSmall.java, app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayerSelectorAdapter.java, app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayerSelectorDialog.java
Play buttons now should be updated by PlayerService's state only.
Since we have PrePlaying state set nearly immediately after
button press - we should not set icons predictively.
=> Fix play-pause icons going out of sync

app/src/main/java/net/programmierecke/radiodroid2/alarm/AlarmReceiver.java
This won't fully solve the issue, e.g. when connection becomes metered
during the playback, however it's still better than nothing.
Without rewriting the alarm code I'd hesitate to improve it further.
See: #744
=> Play system alarm on metered connection if metered warning is enabled

app/src/main/java/net/programmierecke/radiodroid2/FavouriteManager.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentHistory.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerFull.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerSmall.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentStarred.java, app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java, app/src/main/java/net/programmierecke/radiodroid2/station/StationActions.java, app/src/main/java/net/programmierecke/radiodroid2/utils/RecyclerItemSwipeHelper.java, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
- Disable flinging and reduce swipe threshold for station lists
- Removal from favourites now shows undo snackbar in most cases
- Increase undo snackbars duration to 6 seconds
@Vrihub this should fix all you troubles with removal from favourites.
<strike>I also want to fix snackbar theming in dark mode.</strike> Done
=> Improve the process of removal from favourites

app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerFull.java, app/src/main/java/net/programmierecke/radiodroid2/Utils.java
Previously nothing happened after permissions were granted.
=> Start recording after storage permissions are granted

app/build.gradle, app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/ExoPlayerWrapper.java, app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/IcyDataSource.java, app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/RadioDataSourceFactory.java, app/src/main/java/net/programmierecke/radiodroid2/station/live/ShoutcastInfo.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/net/programmierecke/radiodroid2/players/exoplayer/IcyDataSourceTest.java, build.gradle
It seems to work just fine. The biggest issue is probably the required increase of minSdkVersion from 15 to 16.
For now I've left all the original callbacks of our `IcyDataSource` and used the original routines to spread the metadata that's now received with the new callback `onMetadata` in `ExoPlayerWrapper`.
One positive effect ist already that the ExoPlayer metadata reader seems to convert some latin encodings to utf8.
I don't know, if we really want or need to make the upgrade, but with this PR we can already play around with it.
=> Upgrade ExoPlayer from 2.9.6 to 2.11.4

app/src/main/res/layout/layout_player_bottom_sheet.xml
Android Q introduced gesture navigation which in combination with
edge-to-edge app mode may cause gestures conflict with bottom sheet.
To fix this in new release of material components
bottom sheet automatically adjust position based on system defined
insets. However it doesn't know where bottom sheet actually is
and if the app supports edge-to-edge mode.
Since we don't support edge-to-edge mode - we could just disable
this new feature of bottom sheet.
Closes: #798
See:
- https://github.com/material-components/material-components-android/commit/4e28d9c9162d8f4c73dfa1b397f52ef5e32ed726 
- https://medium.com/androiddevelopers/gesture-navigation-handling-visual-overlaps-4aed565c134c
- https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e
@morckx Could you …
=> Fix bottom sheet positioning on Android Q

app/src/main/java/net/programmierecke/radiodroid2/FragmentPlayerSmall.java, app/src/main/res/menu/menu_player.xml
Fixes #799
The menu entry is not adapted correctly to "remove from favorites" if a
station is already bookmarked and it is obsolete here anyway, having
already the large star button at the bottom for (un-)bookmarking.
=> Remove add to favorites menu entry in full player

app/src/main/res/values-es/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
This bug was already introduced in 4703dce0f1657c7a803cb943acf0db0a772f7199 and had often confused me.
I don't know if Chinese, Danish and Indonesian are also affected.
=> Fix wrong string values for giving_up_resume

app/src/main/res/values-es/strings.xml
See
https://github.com/segler-alex/RadioDroid/pull/800#discussion_r417601646
Edit: fixes #810
=> Fix duplicate strings in Spanish translations

.github/workflows/android-ci.yml
I don't know if this is already perfectly configured, but it should already help avoiding issues like #810 as pull requests will be automatically checked and marked accordingly.
=> Add github action to perform CI tests on pushes and pull requests

app/src/main/java/net/programmierecke/radiodroid2/station/StationActions.java
This allows for sharing links also via messengers, e-mail clients, etc.
On newer Androids the sharing also with audio players, such as VLC,
seems improved and there is an option to copy links to the clipboard.
Fixes #39 and fixes #812 (see also #809)
=> Share station links as text

app/src/main/AndroidManifest.xml
Fixes #817
See
https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df
=> Fix recording on Android 10

.github/workflows/re-run-pull-request-github-actions.yml
This should run all CI tests on open pull requests whenever the master branch is updated.
@segler-alex : if you want to test or merge this, you first need to create a Personal Access Token here https://github.com/settings/tokens , if you haven't yet. 
Don't ask me about the necessary scopes. Apparently, I intuitively chose a sufficient superset, but I don't know if it is minimal.
Copy the token and add a new secret with the name _PAT_ here:
https://github.com/segler-alex/RadioDroid/settings/secrets and paste the token from the clipboard into the value field.
=> Re-run CI tests on open PRs when master changed

app/src/main/java/net/programmierecke/radiodroid2/players/PlayStationTask.java
With this change, depending on the actual stream type, dedicated radio and audio stream players like VLC, XiiaLive, and Yatse are offered as external players. Without apparently only apps that handle urls in general.
```
share.setDataAndType(Uri.parse(url), "audio/*")
```
Overrides the MIME type that would ordinarily be inferred from the data.
This is not the case with:
```
share.setType("audio/*"); // redundant on some APIs
share.setData(Uri.parse(url));
```
See:
https://developer.android.com/reference/android/content/Intent#setDataAndType(android.net.Uri,%20java.lang.String)
=> Fix choice of external audio players

app/build.gradle, app/src/main/java/net/programmierecke/radiodroid2/station/ItemAdapterStation.java, app/src/main/res/layout/stub_list_item_station_details.xml, app/src/main/res/values/strings.xml
Note that you cannot delete a station from the favorites via the station detail buttons anymore. For this our nice swipe to delete in the favorites view should be used. I think, all in all the pros outweigh the cons here.
-------
Starring/adding to favourites is of course still possible. In addition, note the button for external player that is shown when internal player is configured:
=> Align station detail actions with those of the icon only popup menu

app/src/main/java/net/programmierecke/radiodroid2/Utils.java, app/src/main/java/net/programmierecke/radiodroid2/players/exoplayer/ExoPlayerWrapper.java, app/src/main/java/net/programmierecke/radiodroid2/players/mediaplayer/MediaPlayerWrapper.java, app/src/test/java/net/programmierecke/radiodroid2/UtilsTest.kt
Fixes #833
Some streams have a query after the path, like:
https://stream.revma.ihrhls.com/zc5260/hls.m3u8?streamid=5260
In the long run, we should probably have a more thorough detection or try switching if ExoPlayer can't detect the encoding, but for now this should work.
=> Fix false negatives in hls stream detection

app/build.gradle
Shrinks free debug build by almost 10%.
=> Remove redundant full expoplayer library

app/src/main/java/net/programmierecke/radiodroid2/players/selector/PlayerSelectorAdapter.java, app/src/main/res/drawable/ic_stop.xml, app/src/main/res/layout/list_item_mpd_server.xml
While pause is enough in most cases, there is a case where stop
is not only better, but a necessity - mpd server with Alsa.
Unless playback is stopped mpd server won't release Alsa device.
Closes: #870
=> Add stop button to MPD

app/src/main/res/values-it/strings.xml
The Italian translation in f9edae5 didn’t escape apostrophes as the Android tooling requires; this change fixes that issue.
=> Escape apostrophes in the Italian translations

app/build.gradle, app/src/androidTest/java/net/programmierecke/radiodroid2/tests/UILangTest.java
This would prevent the addition of new broken translation.
Otherwise, a new translation which is broken in runtime
would pass UI tests.
=> Test all available languages instead of an open-coded list

.github/workflows/android-instrumented-tests-ci.yml, app/build.gradle, app/src/androidTest/java/net/programmierecke/radiodroid2/tests/UILangTest.java
1) Recently instrumented CI started to fail with:
Error: Unable to process command '::set-env name=ANDROID_HOME,::/Users/runner/android-sdk' successfully.
2) Bumping of androidx.test:runner androidx.test:rules resulted in an error:
AAPT: error: attribute android:forceQueryable not found.
3) .test.BuildConfig doesn't contain configs set in gradle
4) Starting of the instrumented app stucked somewhere after a bump of
com.squareup.okhttp3:mockwebserver for unknown reason, revert it for
now.
=> Fix espresso tests failure on CI

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/net/programmierecke/radiodroid2/RadioDroidApp.java, app/src/main/java/net/programmierecke/radiodroid2/utils/TvChannelManager.kt
This merge request adds an Android TV feature making starred programmes available on the home screen.
The channel is created as non-browseable by default since when a channel doesn’t have any programmes, it shows a button launching the application itself — probably not what a user wants if they never used the app and never starred any stations.
As a first station is starred, `TvChannelManager` requests the system to make the channel browseable. This works for the first channel the application creates *only*, which is why the channel is never removed — if we recreate a channel, it won’t be shown on the home screen and the user will have to make it visible manually.
The APIs this code uses are available since the API level 26 only, and the library wrapping them needs minimal SDK version 21; …
=> Android TV: show starred stations as a home screen channel

app/src/androidTest/java/net/programmierecke/radiodroid2/tests/UINotificationTests.java, app/src/androidTest/java/net/programmierecke/radiodroid2/tests/UIRotationTest.java, app/src/androidTest/java/net/programmierecke/radiodroid2/tests/utils/TestUtils.java, app/src/main/aidl/net/programmierecke/radiodroid2/IPlayerService.aidl, app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java, app/src/main/java/net/programmierecke/radiodroid2/service/PlayerServiceUtil.java
We want to have a binder interface as long as PlayerService is alive
because PlayerServiceUtils is used indirectly from the service.
Thus, we only should unbind the service when its shutdown is explicitly
requested.
Now service is started via Context.bindService without calling
Context.startService beforehand, which wasn't doing what probably
was expected. Since bindService didn't wait for startService
completion.
Closes: #972
=> Fix PlayerService destruction on orientation change

app/src/main/java/net/programmierecke/radiodroid2/Utils.java
The server fallback is activated only if `downloadFeed` returns `null`, which previously happened only if an exception was thrown. This happens e.g. if the server is totally offline and thus the connection times out, but it doesn’t happen if the server is online but doesn’t work (which is the case right now: https://de1.api.radio-browser.info/ is online, but reports 503 Service Unavailable). Change `Utils.downloadFeed()` to log an error and return `null` if there is an HTTP response, but it’s unsuccessful (i.e. the status code is not in the 2xx range). Returning `null` triggers the fallback mechanism.
=> Fix server fallback

app/src/main/java/net/programmierecke/radiodroid2/ActivityMain.java, app/src/main/java/net/programmierecke/radiodroid2/StationSaveManager.java
This fixes the load/save of favourites and history list on android >= 13.
The idea is to fallback to simple save that does not need user rights and also just use the system dialog.
This should also work on older versions of android if the rights are not given.
=> saving working
